version: 2

sources: 

  - name: raw_python
    database: raw
    schema: python
    tables: 
      # - name: art_blocks_sales
      # - name: bayc_transfers
      # - name: crypto_punk_sales
      # - name: crypto_punk_transfers
      
      - name: open_sea_sales
